export const language = {
  en: {
    seller: "Seller Page",
    downloadApp: "Download App",
    connect: "Connect",
    noti: "Notifications",
    notiRecent: "Notifications Recent",
    help: "Help",
    findInShop: "Find In Shop",
    noProduct: "No Product",
    sale: "Sale",
    tshirt: "Men's clothes",
    timeSale: "Time sales",
    saleCode: "Sale Code",
    productNation: "Product nation",
    caterogy: "Category",
    login: "Login",
    register: "Register",
    vietnam: "Vietnamese",

    allCategory: "All Categories",
    popular: "Popular",
    new: "New",
    selling: "Selling",
    price: "Price",

    share: "Share",
    like: "Liked (27.5K)",
    evaluate: "Evaluate",
    bought: "Bought",
    report: "Report",
    chip: "Chip",
    insurance: "Insurance",
    insuranceMorther: "Mother & baby fashion insurance",
    moreInfo: "More info",
    delivery: "Delivery",
    deliveryPrice: "Delivery Price",
    count: "Count",
    addCart: "Add To Cart",
    buyNow: "Buy Now",

    cart: "Cart",
  },
  vi: {
    seller: "Trang bán hàng",
    downloadApp: "Tải App",
    connect: "Kết nối",
    noti: "Thông báo",
    notiRecent: "Thông báo mới nhận",
    help: "Trợ giúp",
    findInShop: "Tìm trong Shop",
    noProduct: "Chưa có sản phẩm nào",
    sale: "Giảm giá",
    tshirt: "Thời trang nam",
    timeSale: "Khung giờ săn sale",
    saleCode: "Mã giảm giá",
    productNation: "Hàng quốc tế",
    caterogy: "Danh mục",
    login: "Đăng nhập",
    register: "Đăng kí",
    vietnam: "Tiếng Việt",
    allCategory: "Tất cả danh mục",
    popular: "Phổ biến",
    new: "Mới ",
    selling: "Bán chạy",
    price: "Giá",
    share: "Chia sẻ",
    like: "Dẫ thích (27.5K)",
    evaluate: "Đánh giá",
    bought: "Đã bán",
    report: "Báo cáo",
    chip: "Gì cũng rẻ",
    insurance: "Bảo hiểm",
    insuranceMorther: "Bảo hiểm Mẹ & Bé",
    moreInfo: "Tìm hiểu thêm",
    delivery: "Vận chuyển",
    deliveryPrice: "Phí vận chuyển",
    count: "Số lượng",
    addCart: "Thêm vào giở hàng",
    buyNow: "Mua ngay",
    cart: "Giỏ hàng",
  },
};
