export const language = {
  en: {
    seller: "Seller Page",
    downloadApp: "Download App",
    connect: "Connect",
    noti: "Notifications",
    notiRecent: "Notifications Recent",
    help: "Help",
    findInShop: "Find In Shop",
    noProduct: "No Product",
    sale: "Sale",
    tshirt: "Men's clothes",
    timeSale: "Time sales",
    saleCode: "Sale Code",
    productNation: "Product nation",
    caterogy: "Category",
    login: "Login",
    register: "Register",
  },
  vi: {
    seller: "Trang bán hàng",
    downloadApp: "Tải App",
    connect: "Kết nối",
    noti: "Thông báo",
    notiRecent: "Thông báo mới nhận",
    help: "Trwoj giúp",
    findInShop: "Tìm trong Shop",
    noProduct: "Chưa có sản phẩm nào",
    sale: "Giảm giá",
    tshirt: "Thời trang nam",
    timeSale: "Khung giờ săn sale",
    saleCode: "Mã giảm giá",
    productNation: "Hàng quốc tế",
    caterogy: "Danh mục",
    login: "Đăng nhập",
    register: "Đăng kí",
  },
};
